# --- Base image ---
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Define build arguments for Vite
ARG VITE_APP_API_URL
ARG VITE_EXPORT_API_URL
ARG VITE_MICROSERVICES_API_URL

# Set environment variables
ENV VITE_APP_API_URL=$VITE_APP_API_URL
ENV VITE_EXPORT_API_URL=$VITE_EXPORT_API_URL
ENV VITE_MICROSERVICES_API_URL=$VITE_MICROSERVICES_API_URL

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Start Vite dev server on all network interfaces directly from Dockerfile
CMD ["npx", "vite", "--host", "--port", "5173"]
