spring.application.name=cryptocurrency-analysis-app

# 1. MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/crypto_db}
spring.mongodb.database=${MONGODB_DATABASE:crypto_db}
spring.data.mongodb.auto-index-creation=true